name: python lint and test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        architecture: "x64"
        cache: "pip"
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: lint with flake8
      run: |
        poetry install --group dev
        poetry run flake8 .
    - name: lint with isort
      run: |
        poetry install -group dev
        poetry run isort .
    - name: lint with black
      run: |
        poetry install --group dev
        poetry run black .
    - name: test with pytest
      run: |
        poetry install --group dev
        poetry run pytest
